import type {Metadata} from "next";
import {Inter, Roboto} from "next/font/google";
import "./globals.scss";
import {HistoryProvider} from "@/context/history";
import {UniversalPromptProvider} from "@/context/universal";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chat-bot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <HistoryProvider>
        <UniversalPromptProvider>
          <body className={`${roboto.variable} ${inter.variable} antialiased`}>
            {children}
          </body>
        </UniversalPromptProvider>
      </HistoryProvider>
    </html>
  );
}
